USE CarService
GO

CREATE TABLE TaskForCar(
	TaskForCarId INT IDENTITY(1,1),
	CarId INT NOT NULL REFERENCES Car(CarId) ON DELETE CASCADE ON UPDATE CASCADE,
	RepairmanId INT NOT NULL REFERENCES Repairman(RepairmanId) ON DELETE CASCADE ON UPDATE CASCADE,
	VehicleMalfunction NVARCHAR(500) NOT NULL,
	Cost FLOAT NOT NULL,
	StartDate DATETIME NOT NULL DEFAULT(getdate()),
	FinishDate DATETIME NULL,
	CONSTRAINT PK_TaskForCar_TaskForCarId PRIMARY KEY CLUSTERED (TaskForCarId)
)
GO